buildingDict = {
    "wood": "1",
    "clay": "2",
    "iron mine": "3",
    "crop": "4",
    "sawmill": "5",
    "brickyard": "6",
    "iron foundry": "7",
    "grain mill": "8",
    "bakery": "9",
    "warehouse": "10",
    "granary": "11",
    "smithy": "13",
    "tournament square": "14",
    "main building": "15",
    "rally point": "16",
    "marketplace": "17",
    "embassy": "18",
    "barrack": "19",
    "stable": "20",
    "workshop": "21",
    "academy": "22",
    "cranny": "23",
    "town hall": "24",
    "residence": "25",
    "palace": "26",
    "treasury": "27",
    "trade office": "28",
    "great barrack": "29",
    "great stable": "30",
    "city wall": "31",
    "earth wall": "32",
    "palisade": "33",
    "stonemason": "34",
    "brewery": "35",
    "trapper": "36",
    "great warehouse": "38",
    "great granary": "39",
    "world of wonder": "40",
    "horse drinking trough": "41",
    "water ditch": "42",
    "natarian wall": "43",
    "hidden treasury": "45",
}

unitDict = {
    1: {
        "legionnaire": "1",
        "praetorian": "2",
        "imperian": "3",
        "equites legati": "4",
        "equites imperatoris": "5",
        "equites caesaris": "6",
        "ram": "7",
        "fire catapult": "8",
        "senator": "9",
        "settler": "10",
        "hero": "11",
    },
    2: {
        "clubswinger": "1",
        "spearman": "2",
        "axeman": "3",
        "scout": "4",
        "paladin": "5",
        "teutonic knight": "6",
        "ram": "7",
        "catapult": "8",
        "chief": "9",
        "settler": "10",
        "hero": "11",
    },
    3: {
        "phalanx": "1",
        "swordsman": "2",
        "pathfinder": "3",
        "theutates thunder": "4",
        "druidrider": "5",
        "haeduan": "6",
        "ram": "7",
        "catapult": "8",
        "chief": "9",
        "settler": "10",
        "hero": "11",
    },
}

tribeName = {1: "Roman", 2: "Teuton", 3: "Gauls"}

tribeOffset = {1: 0, 2: 10, 3: 20, 4: 30, 5: 40}
